### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
# Content-Type: application/json

# {
#     "titulo": "Estudar Node.js",
#     "descricao": "Estudar Node.js para desenvolver aplicações web",
#     "categoriaId": "7cc904b2-8b25-4535-8e6c-5c34e9923bda"
# }

### Alterar Tarefa existente
PUT http://localhost:5000/api/tarefas/alterar/1

### Listar Tarefas nao concluidas
GET http://localhost:5000/api/tarefas/naoconcluidas

### Listar Tarefas conlcuidas
GET http://localhost:5000/api/tarefas/concluidas